#267 new parent is child in objects
mp-co-ru/mpc-peresvet pull request #275
Opened 2024-03-18 18:41 UTC by VVB-Github

Добавил обработку случая, когда новый родитель узла находится в подиерархии изменяемого его же

2024-03-19 13:36 UTC, Vovaman requested changes
Внести исправления согласно комментариям.

2024-03-19 13:36 UTC, Vovaman commented on src/common/model_crud_svc.py
> +    async def _updating(self, mes) -> Union[dict,None]:
В питоне 3.10 можно не использовать Union. 
Запись ``Union[dict,None]`` можно сделать так: ``dict | None``.
Соответственно, убери и строку 13

2024-03-19 13:36 UTC, Vovaman commented on src/common/model_crud_svc.py
> +                error={"response": "Новый родительский узел содержиться в подиерархии"}
Ошибка: "Узел что делаеТ?" -> "содержиТСя", без мягкого знака.
Кроме того, ты формируешь ошибку, но в объекте нет ключа "error", поэтому это у тебя не обработается классом ErrorHandler. Во-первых, надо изменить. Во-вторых, получается, что ты не проверял, что написал, не посылал запросы. Такой код пушить нельзя.

2024-03-19 13:36 UTC, Vovaman commented on src/services/objects/api_crud/objects_api_crud_svc.py
> +        if res["response"]== "Новый родительский узел содержиться в подиерархии":
содержиТСя

2024-03-19 13:36 UTC, Vovaman commented on src/services/objects/api_crud/objects_api_crud_svc.py
> +            raise HTTPException(status_code=400, detail="Новый родительский узел содержиться в подиерархии")
см. выше

2024-03-19 13:36 UTC, Vovaman commented on src/services/objects/api_crud/objects_api_crud_svc.py
> +    return res
Что используешь Depends - молодец.
Только давай так: вот такая обработка ошибок - она общая для всех сервисов.
Поэтому логично вынести её в базовые классы.
Логика работы сервисов и класса ErrorHandler тогда такая: если запрос прошёл нормально, сервис в теле ответа, кроме того, что уже описано, делает ключ "error", в котором есть ключ "id", который равен 1xx или 2хх (https://ru.wikipedia.org/wiki/Список_кодов_состояния_HTTP). Если же произошла ошибка, то код уже 4xx или 5xx. ErrorHandler проверяет этот код и фигачит или не фигачит ошибку с тем сообщением, которое записал сервис в ключе "error". Кроме того, в сообщение по ошибке давай ориентироваться на формат, который генерит pydantic:
```json
{
    "detail": [
        {
            "type": "list_type",
            "loc": [
                "body",
                "attributes"
            ],
            "msg": "Input should be a valid list",
            "input": {
                "cn": "Состояние",
                "prsMethodAddress": "state"
            },
            "url": "https://errors.pydantic.dev/2.1/v/list_type"
        }
    ]
}
```

2024-03-19 13:45 UTC, VVB-Github commented on src/common/model_crud_svc.py
> +                error={"response": "Новый родительский узел содержиться в подиерархии"}
обрабатывается - вот код из `objects_api_crud_svc.py`
`if res["response"]== "Новый родительский узел содержиться в подиерархии":`

2024-04-16 10:09 UTC, Vovaman commented on src/services/objects/api_crud/objects_api_crud_svc.py
> +    await error_handler.handle_e406(res)
Исходя из исправленного выше кода класса ErrorHandler код изменится на 

```python
async def create(payload: ObjectCreate, error_handler: svc.ErrorHandler = Depends()):
    res = await app.create(payload)
    await error_handler.handle_error(res)
```
Причём последняя строка будет и в других методах (update и т.д.). Причем везде одна и та же.

2024-04-16 10:09 UTC, Vovaman commented on src/services/objects/api_crud/objects_api_crud_svc.py
> +    return res
См. комментарий к методу create

2024-04-16 10:09 UTC, Vovaman commented on src/services/objects/api_crud/objects_api_crud_svc.py
> +    return res
...Похоже, требование на наличие ключа "error" в нормальных ответах отменяется.

2024-04-27 09:59 UTC, merged