Дока на алерты (не окончательная)
mp-co-ru/mpc-peresvet pull request #347
Opened 2024-07-01 07:11 UTC by VVB-Github

2024-07-01 12:45 UTC, VVB-Github commented
Сделал в основные части доков по тегам, алертам, объектам (но конечно же там множество мелочей которые предстоит править). В целом я верно все делаю? Есть важные моменты которые я упустил?

2024-07-01 22:44 UTC, VVB-Github commented
getLinkedTags connectors
getLinkedTags в запросе на вывод коннекторов не влияет на ответ на запрос

2024-07-01 23:30 UTC, VVB-Github commented
PUT connectors
не работает отвязка тегов (может повлияло то, что у меня 1-н тег был привязан к 2-м коннекторам?)

2024-07-02 01:19 UTC, VVB-Github commented
dataStorages POST
не работает (запрос был такой и при его посылке постман бесконечно ждет ответа)
{
    "linkTags": [{
        "tagId":"6f18cafa-b2da-103e-83c0-b9a6d48c0bf6",
        "attributes": {
            "cn": "test_connected_tag",
            "description": "test_teg",
            "objectClass":""
        }
    }],
    "linkAlerts": [{
        "alertId": "4d440216-c809-103e-8748-05e8cc7fd715",
        "attributes": {
            "cn": "test_connected_alert",
            "description": "test_alert",
            "objectClass":""
        }
    }],
    "attributes": {
        "cn": "dataStorage_test",
        "description": "test_DS"
    }
}
и как следствие пока что доку на dataStorages не сделал

2024-07-02 01:31 UTC, VVB-Github commented
Schedules POST
Также проблемы с созданием расписаний. Выдает такую ошибку - ERROR    :: Сервис `schedules_model_crud`. Неизвестное действие schedules.create.
Как следствие документацию пока что не написал

2024-07-02 01:40 UTC, VVB-Github commented
И пока не очень понимаю как pandas API работает. Теперь для дальнейшего написания документации надо чинить dataStorages, schedules, alerts (и в pandas разобраться)

2024-07-02 17:19 UTC, Vovaman requested changes

2024-07-02 17:53 UTC, VVB-Github commented on docs/source/samples/alerts/getAlertsIn.txt
> +POST /v1/alerts/ HTTP/1.1
Т.е. привести пример строки запроса?

2024-07-02 17:54 UTC, VVB-Github commented on docs/source/samples/alerts/putAlertOut.txt
> +    "пустой словарь в случае успешного запроса",
Тем не менее скомпилировалось. Но изменить можно

2024-07-05 10:00 UTC, Vovaman commented
Убрать из всех примеров конкретные id узлов, заменив их на строки вида "<tag id>".
Исправить ``{null}`` на просто ``null``.

2024-07-15 19:39 UTC, Vovaman approved these changes

2024-07-15 19:40 UTC, merged